name: Load articles

on:
  schedule:
    - cron: "* * * * *"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Reset with main
        run: git reset --hard origin/main

      - name: Build
        run: load.sh > index.html
